apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: tools
    labels:
        app.kubernetes.io/part-of: gitops-k8s-platform
        app.kubernetes.io/name: grafana
type: Opaque
stringData:
    #ENC[AES256_GCM,data:6fViMSgD12BV5E3OHgX5/az77dnAhpFNsUw2LIgRf+KeKme7FeRewmZpVPVdRTfxryNr5qTTZt8Z1y+3xJlbAAV2Fq5/iDyOGbkO,iv:YsWZV1s9+KcHhOabMQ9/fm0bNi7QMXNskhuQq9mXdT4=,tag:V/q/U/hS1VNEDHsVK7HlAg==,type:comment]
    admin-user: ENC[AES256_GCM,data:7MUr5SQ=,iv:HUlztG0PL12kr6mP5MFT6JL6HaijAbFOuphtaW/MYH0=,tag:dpn7/iU8yM9KyFcV71bnPg==,type:str]
    admin-password: ENC[AES256_GCM,data:UrscWPW2NakE7/CTTgoRBqWfY8Fmwh0=,iv:tjW67OFdZMjttW5EDsh7Jg0zATbqnGlBrQLSYmfhCi4=,tag:dXTvsBxA8nslMsA/Vtq++w==,type:str]
    #ENC[AES256_GCM,data:yMoeX1VaRpg5+ZC5hmHAYZQrTN3WYhkRtuW4WMCQ3pqANOnQUysD7PkK6z+Rtzeh9ueLgcpRAvDqlkIG,iv:D/3Q8QhggBjfW65eonrpR4nkVTv37qj7mcgV0fr4XRk=,tag:o854oU+z128z8TG2/q2+sQ==,type:comment]
    #ENC[AES256_GCM,data:b/mH+FQlMcuhpe2XkgFlMbbijAhf/WshCxwPcELP2z7ZosJlji7+qav86JqWUqewQ36TfaMCdit8g3dboQFj2dUSwaLV0g==,iv:9r20nCM+Cuj2vwgMA9T+gGfutsLb+MnLDbfCHfduVfs=,tag:vDKbAc7ZKscblfJEfgCZTQ==,type:comment]
    oidc-client-secret: ENC[AES256_GCM,data:FW3X2x9o6/RF0oBkc0qm3Wri5f8lk4bDrkNzYQ==,iv:19W7FhGdTJTAuAygUdPO6llelZHniCRuoYJX92+RV4c=,tag:dwkUPbVNeJspdlF2BaeMZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuV2VFdXlwM2Q0bUFFSUdh
            WC8vb0xiVzJyNW1vZFBCcDZ3SHRCbHlYZDI4CmZha081V25tbVF6T0MwWklEMXhC
            VWM3YjZPVlMxa0w2cUorREd6VHRFN1kKLS0tIDJSL2QrRkFUeXJpbjdZalBzRWg0
            QkttSzcreU5ST041THVaQ3AwOE1PNjgKBKSxm0f+xzgDNjigShyohBwZkUmm5P9k
            J82fNHpOws6WUdDFWDJ7TUkOt+sESH06L/uVsRaNbedtQyY/2tqhNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16944yhg8mqpwr4w609lj9xeg0ufxzwzea5hdma0047q33s6dhepqua8sjj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T17:11:35Z"
    mac: ENC[AES256_GCM,data:6HfmxiiggMAKDZPRXADX9K1Bmu8O5W3wQNmv7WTRO9HhAbmJuWzMqif+V+DebNlmFkhFHSsntpIQHkEd92owf6yb45mmphjHs/GcTa2oz5WgS+OzjDZgmOtxoBNguXAQovad32CtjQe9mPyEo1SiUuS743Ly2UZwdCW9g6TSxDo=,iv:JQ7CEv12KdPviZpd+OG5qi7M7KIKOSGPTUieYscT3zE=,tag:8KdRXdCDK5BoDCFslOO+mA==,type:str]
    version: 3.13.1
