apiVersion: v1
kind: Secret
metadata:
    name: headlamp-secret
    namespace: tools
    labels:
        app.kubernetes.io/part-of: gitops-k8s-platform
        app.kubernetes.io/name: headlamp
type: Opaque
stringData:
    #ENC[AES256_GCM,data:H9XiJ0s8M44c/fN2hY/3zadBAE2DT+3UYUs0+d+I59MPbrD3e89e048MKKcE6h+dyqbLHw2MbYEH0i4qjXh9VTDgOVTWSc8=,iv:ZH/0OTaQ25ydCabXKZpESF4Y+sq2WP6nJYHMV4Nm4wI=,tag:7R25uWUJwO8Bju33sWEq3A==,type:comment]
    HEADLAMP_CONFIG_OIDC_CLIENT_ID: ENC[AES256_GCM,data:YowCV/IiUBg=,iv:M+LyAzJXvA4g3NT61oTEArU1nFFh1f3cIpw+CaZJV6Y=,tag:Gt1sndNVTVMyFyE5nPOwnw==,type:str]
    HEADLAMP_CONFIG_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:hGD8rrc34Cb5xpXYIQtmz6omGa4q0dpRAPCLZd4=,iv:dAjw/Myz7stjzEEFJSsGfpOJfGNgg7bxAj7YI4Ek2V0=,tag:1wEGGaHDPfTnT+Nt9YY54g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL0VnUXBEdWpWN1ZtZHN5
            eXd5ZUJSQmkwV1gvb3cycVo4Mkd4Wlc0aHpZCkJLSlNkM1lxYjdUZkFDSU0rN2ZL
            d0hIMnVxRWQ4N1hSL2VJNHY0c29zdmcKLS0tIGwva3lqdS8xNTRjeTJUN2E4cUdW
            aW4zZkxid0hoWldteGVvbHZ6TmVhaTQKh91FWWyAV3lsJjCoqMB7RERHiQpYy0vO
            wjHeBL++vSon1uB2n209IRbPHeMpSeMGcGVFkSNAScRbdD4PZChCVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16944yhg8mqpwr4w609lj9xeg0ufxzwzea5hdma0047q33s6dhepqua8sjj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T17:11:35Z"
    mac: ENC[AES256_GCM,data:OYfcs5psftLAteCMB9BYFgru5EWExdVilx265OTf0VU5fFdWamQCdZZEmTNFc8heYc4rw1VBomCdRewio1jkYgDPrJOrK556t8jhe6xPNFP6z0uOsITsIc0HSyh5PK8bheUqBgeaverKjG6uKgUNdyplYHyYE9UFyEioSKuRT0s=,iv:ZBGtRC3ExV4Je1t87YNd55ENBh0iVLbQY4GUYVuYpSU=,tag:MrtcPaeJ/ENnEPl8KkFsxw==,type:str]
    version: 3.13.1
