apiVersion: v1
kind: Secret
metadata:
    name: dex-secret
    namespace: dex
    labels:
        app.kubernetes.io/part-of: gitops-k8s-platform
        app.kubernetes.io/name: dex
type: Opaque
stringData:
    #ENC[AES256_GCM,data:yJexbQkgENFKeB09R1ETsMtty5Nrbrwkn7lZ0yQkqYN52XkPC+yZIqoggv9Ym5DZ8/HHKqaBpBsAQ5HtJjvU7/vG4WHrYM90eQ==,iv:JtpPc90GCz968m0g6jpLp/oRB+qdvVoTSOIq0zHPFm8=,tag:aff9RRj6EQ52vJuKaOaZFg==,type:comment]
    static-password-hash: ENC[AES256_GCM,data:pYtSQn4alEXbvK0gbDHE8DVly6OQTU/L/hHOUP9jC1es8IIYyi7VGCx4o7n/6+9RkaG65siS25VW3nXfQ68=,iv:D4XR4VEJKPAwV/4pGVqK2j4bdYASqVAve3wwLymHPbA=,tag:OsLwjdV8aJobpUIiXc8xpQ==,type:str]
    static-user-email: ENC[AES256_GCM,data:XRNxt8trKhZfmvdWLauHcQ==,iv:+W6ERCZue54Ae3vKohb+HxvPxTr9JP9x8A7rxzntrXY=,tag:EhoTiYOmiemxCWI1gBoMpA==,type:str]
    static-user-name: ENC[AES256_GCM,data:xqxj83w=,iv:KmQk0RTcfNNKUtUlUY5pf+x5a+WkcVfPM1ASqfvVw30=,tag:sImBpLwaytLH6omKNQvGOA==,type:str]
    grafana-client-secret: ENC[AES256_GCM,data:18DRmEtjmeZvmls4ymkgppFyogvthncLYffIFA==,iv:q2l8mLPPfC2ZYgIHjy3psGLt/+u3AT3UOUB9WD00j58=,tag:aRd3lMntZJkD/ZYoHP/ZTA==,type:str]
    pgadmin-client-secret: ENC[AES256_GCM,data:V+E1ZhrBhKUfgUbMGZ8d9CPxA3CaJ5qoBvOAnw==,iv:69AocrVCKStgP2lMJ+UlQsv9mQE/rHKW3QlbYqjCIoo=,tag:EQVm/A5wfHV57bNUgz56uA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWGVyb21jZUJYUXZaWlNs
            RDEzL0UzYlI3dTFCYVlWNDVNSnlBL2Jmc1FVCnBjS3R4QkdJTzBqMkMyeG5HTzFP
            RFIzVzQ0eDlUS1dzM1FxVTJsWmZSSVEKLS0tIDdvTkJZQWJTc0p5WEVybUcxRENS
            MlE5TXVZRVhIdnorbmVyTFV5SHlKQ0UKJQ5obD9c4n8X3/YIcyHIhvmkPSFb3heL
            BUGp77gWxh3RypSrcpvPZtK3uBX0gguTNPbVNFDFJLRqeUfF4LTcZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16944yhg8mqpwr4w609lj9xeg0ufxzwzea5hdma0047q33s6dhepqua8sjj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T17:11:35Z"
    mac: ENC[AES256_GCM,data:f5yRQu3Splf6VH+cAATYt5NQIGJUvUWIq3fuxVkG4nYW2nZFI7QHd5nnNsN5J0NqI6G23NNRG7DAsiJfuZ9P03VqzNK2ICsMbaVc2++vfOJQzmpQ3HGykxd2hBowD2plsGgOPiHhebPc8Too8mloqs2bReKIdmqzF+bqjyoN2wU=,iv:XmflAUpToDG8gBhwLB/VBIcyMGp9Irb92IFjnVd+DCk=,tag:TKK+MspsiF+7RKNxh84PWA==,type:str]
    version: 3.13.1
