apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-issuer-selfsigned.yaml
  - dex/secret.sops.yaml
  - grafana-datasources.yaml
  - alloy-config.yaml
  - flux-podmonitor.yaml
  - dashboards
  - kyverno-policies
