apiVersion: v1
kind: Secret
metadata:
    name: letsencrypt-account-key
    namespace: cert-manager
    labels:
        app.kubernetes.io/part-of: gitops-k8s-platform
        app.kubernetes.io/name: letsencrypt
type: Opaque
stringData:
    tls.key: ENC[AES256_GCM,data:9YILYjWRXHm4Nz1wjV7BcsC3dOjwpnZMsBWSk59m9QK4qlLYIsOXkPEvw8cAu1Bonunw44ZMJISRuXc0mut3KeefCIxSSf2j4ln+aslXpnGabPmrZ3szBq9J1C7vF6eTTnEsUC7xiKFUWmRXBi4xcND68A==,iv:vwoiGt/BPpeyxWEnDDJQDX4KFgiiMn8jWdWvCRdrMMM=,tag:FTsKJDpeHUXwrHALrldV8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldlBXdHBSbTVaUHU4Wk1a
            MCtjdERnbiswUzNHYkhHRW0zbE8zTkRLY2lJCkNqMUM3bTNTcmxYZ0V1bDBHZE5V
            REM2K2RSWjN4OS9iRUlKM2pYTFdXUmMKLS0tIE52enlRSDdVOWF3WENVODdrbjQv
            UFdKRWJ5QktmVGVtSitJTjJVL0NaQjQKvuphYfp8CBbwqcZz3D6TH04nzeY1nMbG
            JM3TJUye5Lixx2yv2gfA31pb/BKrTUZZd1B6Fy0baJbr/+6hwkYRag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16944yhg8mqpwr4w609lj9xeg0ufxzwzea5hdma0047q33s6dhepqua8sjj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T17:11:35Z"
    mac: ENC[AES256_GCM,data:0UssZb8qjrgwR8whaIrcbfcK8GVaR+DvBU+86eomTHpaizGUXUR2yjxBJTaqrbyXTrHPz3h+WBSyTiajeJ2DCxtSiZCaLxOkA8fMjQGag2VhfbmYFLOYknE/+on1hzg1CdJAD/mEyiuATj95774xqIXyGo3Mew5JstlAMGucUN8=,iv:vmQRkOmXtbdQPZp00PMHu4IS8rZE+wMWrp3IxfUb5QE=,tag:huDCpTEMAizpuQfqvjKYEA==,type:str]
    version: 3.13.1
