apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
    namespace: tools
    labels:
        app.kubernetes.io/part-of: gitops-k8s-platform
        app.kubernetes.io/name: pgadmin
type: Opaque
stringData:
    #ENC[AES256_GCM,data:a4IhWBGCB4GXGjUg8dHpe3W9+N6R8N8ivCDd181mhbRs,iv:v3wzg1NsFHspdkfJiEgz9ye92qhvM8b39PniQ7tv3HI=,tag:ZohByRKaPPf3LdQiHbydMQ==,type:comment]
    email: ENC[AES256_GCM,data:XGi6w0mF8u3iTY5FKNtKYw==,iv:+u3L6ZapBvj0WoZw/j8+CJpMeb99/2nRFQ1upc/4VUI=,tag:xEEcipINJeNXmJXWj6gung==,type:str]
    #ENC[AES256_GCM,data:vZL5NyOxVHpe8rT2JDeyyRXP5LucszoLHNep0d4x2k8XdGyjY9xk5T9Cji+KP+jWqweGkAhfytfz,iv:EJmB/GOxTxutHAxmnjS9jI3Q4WcXApSOel1YmJ9ifYg=,tag:CUR2GmBu+2kvRRz1TgHWCA==,type:comment]
    password: ENC[AES256_GCM,data:9Cz9CRnEuOyMJlPGlDQ9FrrgxVAGfic=,iv:VtqH7Yg3+2z5bPKRTWWgZLArjcsqMpQAwY4CDHiqz7A=,tag:PNWxRG6xMfru3ZLtG6HeEA==,type:str]
    #ENC[AES256_GCM,data:tHEuhMDWtDTOoTIk29tSlZDe426UAIr2GGvaCOY8sM+qIcsee5Ns6vWmSdSqoGrve+vVrDnc5hsH7GZB0A4=,iv:AOMBwBTTWz+eShafjGPdNwBlfFS/KvTdnQCcWU2Nv9Y=,tag:LB+DKuHMgDOgnmb1eKL4LA==,type:comment]
    #ENC[AES256_GCM,data:e+eMZvsZWZeGw6AYEXUCZiczsW6roa/1Wb1Xg1Go2IfUG++6bUjvPXRtlFmLuTdjSsFGVaoGVc2NHRojcTXMan4p606Wnw==,iv:fe7afkJbwOTxojaH6pBVKqQZNXLukFB9YBzZxxkX+p0=,tag:AV/PyktORrwcxAZI5qVJ8Q==,type:comment]
    oauth-client-secret: ENC[AES256_GCM,data:euQIW47TU6eDxK5gjuzG/EUDpnD023GRKJvqJw==,iv:62D9SDHbeOrhqcl/BQTgw3USJ2fgUlTwWNCjoLQoJrw=,tag:1InkGj8Wl9KzuluiRzGbdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dE5qdlZYYVF0Wm9LYU51
            YTBwZXZXRkQ3Q0NvQTNFNHZqcDVqTEV2cUZrCjFPMXBZZEFtVkpwcG95ckZvT2lE
            TnQzV3FBam1NMU52TTJ2cUx2dTlxMkEKLS0tIFE5V2Jnb015aUp0amVXeUx2Ujhn
            VDFKekdIUE5OUGlIbXhEcHpXL3lGaG8KPCCJA5EnWCqcCHVRZJZ4qZc95YrxqfkM
            PHPEb10RSlGa/E5lVntAuWjTIy1J8VNkhtN3Ojjc8g7QaN2wO5Uz4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16944yhg8mqpwr4w609lj9xeg0ufxzwzea5hdma0047q33s6dhepqua8sjj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T17:11:35Z"
    mac: ENC[AES256_GCM,data:S7xFMvTybLi9/pG+alzzNtveCOSbxI85kEIO09PIDIVw+ggDFZ6yZcEl6v8wFtMZ9RJynoT8n0cTmYVVDt8ipCCfhaxYrGVcGJJvDvW4y8NuzpToD9kmwP/lelCWRe3A30US7LtLN7xZRHpVfuLHqkygifA1QLlFMVf6ZlObSrU=,iv:Nmft4PrRBxgv5Y72VVKE+DBILquX/ZHjz985uPV5Vj8=,tag:l1YlsivE39iCH78ksRvQaQ==,type:str]
    version: 3.13.1
