apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-alloy
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: gitops-k8s-platform
spec:
  interval: 30m
  releaseName: grafana-alloy
  targetNamespace: monitoring
  storageNamespace: monitoring
  chart:
    spec:
      chart: alloy
      # renovate: helm chart "alloy" from repo https://grafana.github.io/helm-charts
      version: "1.10.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: grafana-alloy-values
      valuesKey: values.yaml
